### ISSUE TITLE
Add to .gitignore

### ISSUE THREAD

**Issue by anevins12** [mpsparrow/html-theme-with-WP#1]
Hi Matthew,

Just in case you didn't know, there appear to be sensitive files in your repos. Best to add those files to .gitignore https://github.com/mpsparrow/html-theme-with-WP/blob/master/blog/wp-config.php

**Comment by mpsparrow** [comment]
Thanks for pointing that out @anevins12! I don't know why those even got committed to the repository. I wasn't planning for the WordPress blog to be committed to the repository, I just wanted the theme to be in the repository. I removed the whole blogs folder.

Just a note, it was a localhost website with no real credentials, so I don't think it would have caused any harm. But anyway, thanks for pointing it out.
